# Generated by Django 5.1.7 on 2025-03-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='motion_detected',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='temperature',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensor_value',
            field=models.CharField(default='', max_length=255),
        ),
    ]
