# Generated by Django 5.1.7 on 2025-03-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_remove_sensordata_heart_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='heart_rate',
            field=models.FloatField(default=70.0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='motion_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(default=25.0),
        ),
    ]
