# Generated by Django 5.1.7 on 2025-03-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_alter_sensordata_person'),
    ]

    operations = [
    ]
