# Generated by Django 5.1.7 on 2025-03-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_update_sensordata_model'),
    ]

    operations = [
    ]
